# Generated by Django 5.2.17 on 2026-09-10 09:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Где выполняется привычка",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Во сколько напоминать", verbose_name="Время"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Что именно нужно сделать",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Приятная привычка служит наградой за полезную",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="От 1 до 7 дней",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность в днях",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем вы себя наградите, если не выбрана приятная привычка",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Не больше 120 секунд",
                        validators=[django.core.validators.MaxValueValidator(120)],
                        verbose_name="Время на выполнение в секундах",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Публичные привычки видны всем пользователям",
                        verbose_name="Признак публичности",
                    ),
                ),
                (
                    "last_reminded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Служебное поле: по нему считается, пора ли напоминать снова",
                        null=True,
                        verbose_name="Последнее напоминание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, которой вы себя награждаете",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewarded_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("time", "id"),
            },
        ),
    ]
